name: upnp-server
version: 0.1.1
summary: upload files with WebDAV and serve them via DLNA/UPnP
description: |
    A very minimal UPnP/DLNA server that allows uploads via WebDAV

    The snap ships a minidlna binary and a webserver in DAV mode sharing
    a directory. To make files available via UPnP open dav://localhost/
    (or the IP instead of localhost if you want to manage the files
    remotely) in a file manager and drop media into the dir.
confinement: strict
base: core18

apps:
  minidlna:
    command: run-minidlna
    daemon: simple
    plugs: [network, network-bind]
  webdav:
    command: run-lighthttpd
    daemon: simple
    plugs: [network, network-bind]

parts:
  minidlna:
    source: ./minidlna
    plugin: make
    build-packages:
        - autoconf
        - automake
        - autopoint
        - autotools-dev
        - gcc
        - gettext
        - git
        - libavcodec-dev
        - libavformat-dev
        - libavutil-dev
        - libexif-dev
        - libflac-dev
        - libid3tag0-dev
        - libjpeg-dev
        - libogg-dev
        - libsqlite3-dev
        - libvorbis-dev
  copy:
    plugin: nil
    source: .
    override-build: |
      cp -av run-minidlna $SNAPCRAFT_PART_INSTALL
      cp -av run-lighthttpd $SNAPCRAFT_PART_INSTALL
      cp -av config.sh $SNAPCRAFT_PART_INSTALL
      cp -av default.yaml $SNAPCRAFT_PART_INSTALL
    stage-packages:
        - gawk
        - libavformat57
        - libc-bin
        - libexif12
        - libflac8
        - libid3tag0
        - libjpeg8
        - libstdc++6
        - libuuid1
        - libvorbisfile3
        - lighttpd-mod-webdav
        - locales
    after: [minidlna]
    stage: [-usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6]
  sqlite:
    source: ./sqlite
    plugin: make
    build-packages:
        - gzip
        - tar
        - wget
    after: [copy]
